version: '2'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - "${PWD}/../env/.env" 

  mobile:
    build:
      context: ${PWD}/../
      dockerfile: ./docker/Dockerfile
    command: bash -c "yarn db:sync:force --db_host $${DB_MAIN__HOST}
      && yarn db:seed
      && yarn start:server"
    volumes:
      - "${PWD}/../:/srv/app" # allows using nodemon
    ports:
      - "3100:3100"
      - "3200:3200"
      - "9220:9220" # debugger
    depends_on:
      - db
    env_file:
      - "${PWD}/../env/.env"
    environment:
      DB_MAIN__HOST: db
